#!/usr/bin/env bash
# Generates infra/.env with fresh random secrets for local development.
# Never commit the resulting file. Every secret is unique per machine, so a
# value leaked from one developer's checkout is worthless anywhere else.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "infra/.env already exists — refusing to overwrite. Delete it first to regenerate." >&2
  exit 1
fi

hex() { openssl rand -hex "$1"; }

cat > .env <<ENV
# Generated by scripts/gen-dev-secrets.sh — local development only. Do not commit.
NEXTAUTH_SECRET=$(hex 32)
PII_ENCRYPTION_KEY=$(hex 32)
JWT_SECRET=$(hex 32)
ENCRYPTION_KEY=$(hex 32)
SSO_SECRET=$(hex 32)
ENV

chmod 600 .env
echo "Wrote infra/.env with fresh secrets."
